global:
  nameOverride: "{{ k8s_monitoring_prometheus_name }}"
  fullnameOverride: "{{ k8s_monitoring_prometheus_name }}"
  namespaceOverride: "{{ k8s_monitoring_namespace }}"
  operator:
    enabled: "{{ k8s_monitoring_prometheus_enabled }}"
    image:
      repository: "{{ _k8s_monitoring_prometheus_operator_image_repository }}"
      tag: "{{ k8s_monitoring_prometheus_operator_image_tag }}"
      pullPolicy: "{{ _k8s_monitoring_prometheus_operator_image_pull_policy }}"
    command: "{{ _k8s_monitoring_prometheus_operator_pod_command_override }}"
    args: "{{ k8s_monitoring_prometheus_operator_pod_args_override }}"
    extraEnvVars: "{{ k8s_monitoring_prometheus_operator_pod_extra_env_vars }}"
    extraEnvVarsCM: "{{ k8s_monitoring_prometheus_operator_pod_extra_configmaps }}"
    extraEnvVarsSecret: "{{ k8s_monitoring_prometheus_operator_pod_extra_secret }}"
    extraVolumes: "{{ _k8s_monitoring_prometheus_operator_pod_extra_volumes }}"
    extraVolumeMounts: "{{ _k8s_monitoring_prometheus_operator_pod_extra_volume_mounts }}"
    sidecars: "{{ _k8s_monitoring_prometheus_operator_pod_sidecar_containers }}"
    initContainers: "{{ _k8s_monitoring_prometheus_operator_pod_init_containers }}"
    automountServiceAccountToken: "{{ _k8s_monitoring_prometheus_operator_service_account_automount }}"
    serviceAccount:
      create: "{{ _k8s_monitoring_prometheus_operator_service_account_create }}"
      name: "{{ _k8s_monitoring_prometheus_operator_service_account_name }}"
      annotations: "{{ _k8s_monitoring_prometheus_operator_service_account_annotations }}"
      automountServiceAccountToken: "{{ _k8s_monitoring_prometheus_operator_service_account_automount }}"

    {{- if _k8s_monitoring_prometheus_operator_pod_security_context }}
    
    podSecurityContext: {{ _k8s_monitoring_prometheus_operator_pod_security_context | to_nice_yaml }}
    
    {{- endif }}

    {{- if _k8s_monitoring_prometheus_operator_container_security_context }}

    containerSecurityContext: {{ _k8s_monitoring_prometheus_operator_container_security_context | to_nice_yaml }}

    {{- endif }}

    service:
      type: "{{ k8s_monitoring_prometheus_operator_service_type }}"
      ports:
        http: "{{ k8s_monitoring_prometheus_operator_service_port }}"