---
- name: "Template Prometheus Chart values file"
  ansible.builtin.template:
    src: "Values.yml.j2"
    dest: "{{ _k8s_monitoring_prometheus_chart_values_file }}"
    mode: "0644"
    force: "yes"
  when: k8s_monitoring_prometheus_state == "present"

- name: "Remove blank lines in Prometheus Chart values file"
  ansible.builtin.replace:
    path: "{{ _k8s_monitoring_prometheus_chart_values_file }}"
    regexp: '(^\s*$)'
    replace: ""
  when: k8s_monitoring_prometheus_state == "present"

- name: "Create monitoring namespace"
  kubernetes.core.k8s:
    api_version: "v1"
    kind: "Namespace"
    name: "{{ k8s_monitoring_namespace }}"
    state: "present"
    kubeconfig: "{{ k8s_kubeconfig_path }}"
  when: k8s_monitoring_prometheus_state == "present"

- name: "Install Bitnami Helm Chart from OCI Registry"
  kubernetes.core.helm:
    name: "{{ k8s_monitoring_prometheus_name }}"
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    chart_ref: "oci://{{ _k8s_monitoring_prometheus_chart_registry }}/{{ _k8s_monitoring_prometheus_chart_repository }}/{{ _k8s_monitoring_prometheus_chart_name }}"
    release_namespace: "{{ k8s_monitoring_prometheus_namespace }}"
    state: "{{ k8s_monitoring_prometheus_state }}"
    values_files:
      - "{{ _k8s_monitoring_prometheus_chart_values_file }}"
    wait: yes

- name: "Remove Prometheus CRDs"
  kubernetes.core.k8s:
    api_version: "apiextensions.k8s.io/v1"
    kind: "CustomResourceDefinition"
    name: "{{ item }}"
    state: "absent"
    kubeconfig: "{{ k8s_kubeconfig_path }}"
  with_items: "{{ _k8s_monitoring_prometheus_crds }}"
  when: k8s_monitoring_prometheus_state == "absent"