- name: "Remove Kind Cluster"
  ansible.builtin.command: "kind delete clusters --kubeconfig={{ k8s_kubeconfig_path }} {{ k8s_kind_with_ingress_setup_cluster_name }}"

- name: "Remove the {{ k8s_kind_with_ingress_setup_cluster_name }}-dns-routing-container"
  community.docker.docker_container:
    name: "{{ k8s_kind_with_ingress_setup_cluster_name }}-dns-routing-container"
    state: absent
