---
- name: "Wait for default ServiceAccount to be created"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: default
        namespace: default
    wait: yes
    wait_timeout: 60

- name: "Spawn DNSutils Pod to get DNS servers"
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: dnsutils
        namespace: default
      spec:
        containers:
        - name: dnsutils
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          command:
          - sleep
          - "3600"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
    wait: yes
    wait_timeout: 60

- name: "Get DNS server entry from DNSutils pod with kubectl exec"
  kubernetes.core.k8s_exec:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    namespace: default
    pod: dnsutils
    command: "cat /etc/resolv.conf"
  register: dnsutils_resolv_conf

- name: "Get currently configured DNS servers for {{ ansible_default_ipv4.interface }} interface"
  ansible.builtin.shell:
    cmd: "nmcli dev show {{ ansible_default_ipv4.interface }} | grep 'IP4.DNS' | awk '{print $2}'"
  register: current_dns_servers

- name: "Store currently established connection name for {{ ansible_default_ipv4.interface }} interface"
  ansible.builtin.shell:
    cmd: "nmcli dev show {{ ansible_default_ipv4.interface }} | grep 'GENERAL.CONNECTION' | awk -F':' '{print $2}' | sed 's/^[[:space:]]*//g'"
  register: current_connection_name

- name: "Package the DNS server and search domain into a dictionary"
  set_fact:
    dns_config:
      search: "{{ dnsutils_resolv_conf.stdout_lines[0] | regex_replace('search ', '') | split(' ') }}"
      addresses: "{{ dnsutils_resolv_conf.stdout_lines[1] | regex_replace('nameserver ', '') | split(' ')}}"

- name: "Add currently configured DNS servers to the list of DNS servers"
  set_fact:
    dns_config:
      search: "{{ dns_config.search }}"
      addresses: "{{ dns_config.addresses + current_dns_servers.stdout.split('\n') }}"

- name: "Get the number of next netplan config to be stored on host"
  ansible.builtin.shell:
    cmd: "ls -r1 /etc/netplan | awk '!/{{ k8s_kind_with_ingress_setup_cluster_name }}/' | head -1 | awk -F'-' '{print $1}' | bc"
  register: latest_netplan_config

- name: "Template the netplan config for Kind cluster DNS"
  ansible.builtin.template:
    src: netplan-config.yaml.j2
    dest: "/etc/netplan/0{{ latest_netplan_config.stdout | int + 1 }}-{{ k8s_kind_with_ingress_setup_cluster_name }}-config.yaml"
    mode: '0644'

- name: "Apply the netplan config for Kind cluster DNS"
  ansible.builtin.shell:
    cmd: "netplan apply"

- name: "Toggle the previously established connection for {{ ansible_default_ipv4.interface }} interface"
  ansible.builtin.shell:
    cmd: "nmcli connection up '{{ current_connection_name.stdout }}'"
  when: current_connection_name.stdout != ''