---
_k8s_monitoring_prometheus_chart_registry: "registry-1.docker.io"
_k8s_monitoring_prometheus_chart_repository: "bitnamicharts"
_k8s_monitoring_prometheus_chart_name: "kube-prometheus"
_k8s_monitoring_prometheus_chart_deployment_timeout: 300
_k8s_monitoring_prometheus_chart_values_file: "{{ manifests_and_configs_path }}/prometheus.yaml"

_k8s_monitoring_prometheus_operator_image_repository: "bitnami/prometheus"
_k8s_monitoring_prometheus_operator_image_pull_policy: "IfNotPresent"
_k8s_monitoring_prometheus_operator_image_tag: "0.72.0-debian-12-r1"

_k8s_monitoring_prometheus_operator_pod_command: []
_k8s_monitoring_prometheus_operator_pod_extra_volumes: []
_k8s_monitoring_prometheus_operator_pod_extra_volume_mounts: []
_k8s_monitoring_prometheus_operator_pod_init_containers: []
_k8s_monitoring_prometheus_operator_pod_sidecar_containers: []

_k8s_monitoring_prometheus_operator_service_account_create: true
_k8s_monitoring_prometheus_operator_service_account_automount: true
_k8s_monitoring_prometheus_operator_service_account_name: "{{ k8s_monitoring_prometheus_name }}-operator-sa"
_k8s_monitoring_prometheus_operator_service_account_annotations: {}

_k8s_monitoring_prometheus_operator_pod_security_context: {}
_k8s_monitoring_prometheus_operator_container_security_context: {}

_k8s_monitoring_prometheus_operator_service_type: "ClusterIP"
