---
- name: "Check if Kind Cluster is already created"
  ansible.builtin.command: "kind get clusters"
  register: kind_cluster_list
  changed_when: false
  failed_when: false

- debug:
    msg: "Kind Cluster List: {{ kind_cluster_list.stdout }}"

- name: "Setup Kind Cluster if not created"
  block:
    - name: "Create Cluster config from template"
      ansible.builtin.template:
        src: "cluster.yml.j2"
        dest: "{{ kind_cluster_config_file }}"
        mode: "u=rw,g=r,o=r"

    - name: "Create Kind Cluster"
      ansible.builtin.command: "kind create cluster --config={{ kind_cluster_config_file }} --kubeconfig={{ kubeconfig_path }}"
      register: kind_cluster_create
      changed_when: kind_cluster_create is changed
      failed_when: kind_cluster_create is failed

    - name: "Wait for Kind Cluster to be ready"
      ansible.builtin.command: "kubectl cluster-info --kubeconfig={{ kubeconfig_path }}"
      register: kind_cluster_ready
      until: kind_cluster_ready.stdout.find("is running") != -1
  when: kind_cluster_list.stdout.find(kind_cluster_name) == -1

- name: "Download NGINX Ingress Controller Manifest"
  ansible.builtin.get_url:
    url: "{{ _ingress_cluster_nginx_ingress_manifest_url }}"
    dest: "{{ manifests_and_configs_path }}/ingress-nginx-deploy.yaml"
    validate_certs: false

- name: "Apply NGINX Ingress Controller Manifest"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    src: "{{ manifests_and_configs_path }}/ingress-nginx-deploy.yaml"
    state: "present"
